name: Update Daily Stats
on:
  schedule:
    - cron: "0 0 * * *" # 매일 자동 업데이트
  workflow_dispatch: # 수동 실행 버튼
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          TIMEZONE: Asia/Seoul
